// This file is  generated by Swirl Compiler

#include <iostream>

template < typename Const >
void print(Const __Obj, const std::string& __End = "\n", bool __Flush = true) {
    if (__Flush) std::cout << __Obj << __End << std::flush;
    else std::cout << __Obj << __End;
}

template < typename Iterable >
std::size_t len(Iterable __Iter) {
    std::size_t cnt;
    for (auto const& elem : __Iter) cnt++;
    return cnt;
}
